version: '3.8'

services:
  tempo:
    image: grafana/tempo:latest
    command: --config.file=/etc/tempo-local.yaml
    volumes:
      - ./tempo-local.yaml:/etc/tempo-local.yaml
    ports:
      - "6831:6831/udp"
      - "9411:9411"
      - "55680:55680"
      - "3100:3100"
      - "14250:14250"
    networks:
      - docker-tempo

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - tempo
    networks:
      - docker-tempo

volumes:
  grafana-storage:

networks:
  docker-tempo:
